import Footer from '@/components/footer'
import Header from '@/components/header'


export const metadata = {
  title: 'My playground',
  description: 'Generated by create next app',
}

// Using body instead of main causes runtime error
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <main>
        {children}
      </main> 
     
    </html>
  )
}
